import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import process from "node:process";

const MUTATION_TIMEOUT_MS = 15_000;

const mutations = [
  {
    name: "detach a replacement parser after an old parser error",
    file: "src/connection/index.js",
    before:
      'this._streamError(error.condition || "bad-format");\n    // A synchronous error write can replace the transport before it returns.\n    if (this.#generation !== generation)',
    after:
      'this._streamError(error.condition || "bad-format");\n    if (false)',
    suite: "src/connection/test/close-race.test.js",
    test: "synchronous parser-error response cannot detach a replacement parser$",
  },
  {
    name: "write an old close-hook footer into a replacement stream",
    file: "src/connection/index.js",
    before:
      'await this.#runHooks("close");\n    if (this.#generation !== generation)',
    after: 'await this.#runHooks("close");\n    if (false)',
    suite: "src/connection/test/close-race.test.js",
    test: "delayed close hooks cannot write a footer to a replacement stream$",
  },
  {
    name: "detach a replacement parser after a synchronous close reply",
    file: "src/connection/index.js",
    before:
      "if (this.#generation === generation && this.socket === socket) {\n      this._detachParser();",
    after: "if (true) {\n      this._detachParser();",
    suite: "src/connection/test/close-race.test.js",
    test: "synchronous peer-close footer cannot detach a replacement parser$",
  },
  {
    name: "dispatch a queued event from a replaced socket",
    file: "src/connection/index.js",
    before: "if (this.socket === socket) {\n          handler(...args);",
    after: "if (true) {\n          handler(...args);",
    suite: "src/connection/test/close-race.test.js",
    test: "a preceding old-socket listener cannot detach a replacement transport$",
  },
  {
    name: "dispatch a queued event from a replaced parser",
    file: "src/connection/index.js",
    before: "if (this.parser === parser) {\n          handler(...args);",
    after: "if (true) {\n          handler(...args);",
    suite: "src/connection/test/close-race.test.js",
    test: "a preceding old-parser listener cannot close the replacement stream$",
  },
  {
    name: "mark a later disconnected session offline after an old stop",
    file: "src/connection/index.js",
    before:
      'if (this.#generation === generation) {\n      this._status("offline", el);',
    after: 'if (true) {\n      this._status("offline", el);',
    suite: "src/connection/test/close-race.test.js",
    test: "old stop cannot mark a later already-disconnected session offline$",
  },
  {
    name: "redirect received stream-error shutdown into a replacement session",
    file: "src/connection/index.js",
    before: "if (isStreamError && this.#generation === generation)",
    after: "if (isStreamError)",
    suite: "src/connection/test/close-race.test.js",
    test: "a received stream-error observer cannot redirect shutdown into a replacement session$",
  },
  {
    name: "emit an old close-hook error into a replacement session",
    file: "src/connection/index.js",
    before:
      'if (this.#generation === generation) {\n            this.emit("error", error);',
    after: 'if (true) {\n            this.emit("error", error);',
    suite: "src/connection/test/close-race.test.js",
    test: "old close-hook rejection cannot emit an error into the replacement session$",
  },
  {
    name: "omit the required outgoing IQ id",
    file: "src/connection/index.js",
    before: "tag.attributes.id === undefined || !IQ_TYPES.has(iqType)",
    after: "!IQ_TYPES.has(iqType)",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects missing id before wire/SM$",
  },
  {
    name: "allow an unknown outgoing IQ type",
    file: "src/connection/index.js",
    before: "tag.attributes.id === undefined || !IQ_TYPES.has(iqType)",
    after: "tag.attributes.id === undefined",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects unknown type before wire/SM$",
  },
  {
    name: "ignore serialized outgoing IQ request child count",
    file: "src/connection/index.js",
    before: "iqChildren !== 1",
    after: "false",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects serialized second request child before wire/SM$",
  },
  {
    name: "ignore outgoing IQ result child count",
    file: "src/connection/index.js",
    before: 'iqType === "result" && iqChildren > 1',
    after: "false",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects result with two direct children before wire/SM$",
  },
  {
    name: "omit the required outgoing IQ core error",
    file: "src/connection/index.js",
    before: "stanzaErrors !== 1",
    after: "false",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects serialized missing core error before wire/SM$",
  },
  {
    name: "allow a core namespace as outgoing IQ request payload",
    file: "src/connection/index.js",
    before: "RESERVED_NAMESPACES.has(tag.uri)",
    after: "false",
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send rejects serialized reserved request namespace before wire/SM$",
  },
  {
    name: "apply core IQ requirements to foreign nonzas",
    file: "src/connection/index.js",
    before:
      'this.NS === NS_JABBER_CLIENT && name === "iq" && namespace === this.NS;',
    after: 'name === "iq";',
    suite: "conformance/rfc6120-outgoing-iq.test.ts",
    test: "send leaves foreign IQ-named nonzas outside IQ rules$",
  },
  {
    name: "accept an unregistered generated stanza error type",
    file: "src/xml/lib/stanzaError.js",
    before: "!TYPES.has(tag.attributes.type?.value)",
    after: "false",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized unregistered error type$",
  },
  {
    name: "accept two serialized standard conditions in a generated error",
    file: "src/xml/lib/stanzaError.js",
    before: "conditions !== 1",
    after: "conditions < 1",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized two standard conditions$",
  },
  {
    name: "accept an invalid serialized generated error URI",
    file: "src/xml/lib/stanzaError.js",
    before: "address &&\n        !isIRI(address)",
    after: "false",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get gone checks actual custom write bad %$",
  },
  {
    name: "ignore CDATA in generated error URI validation",
    file: "src/xml/lib/parseDocument.js",
    before: 'parser.on("cdata", onText);',
    after: "",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized CDATA invalid URI$",
  },
  {
    name: "reserialize a generated error after query callbacks",
    file: "src/iq/callee.js",
    before: "value: (writer) => writer(source),",
    after: "value: element.write.bind(element),",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get gone survives original query writer mutation$",
  },
  {
    name: "hide captured generated error children from send observers",
    file: "src/iq/callee.js",
    before: "cursor.append(parsed);",
    after: "",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get send observers see the captured writer tree$",
  },
  {
    name: "allow an unregistered serialized generated error condition",
    file: "src/xml/lib/stanzaError.js",
    before: "!CONDITIONS.has(tag.local)",
    after: "false",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized unregistered standard condition$",
  },
  {
    name: "allow a reserved serialized generated application namespace",
    file: "src/xml/lib/stanzaError.js",
    before: "!tag.uri || RESERVED_NAMESPACES.has(tag.uri)",
    after: "false",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized reserved application namespace$",
  },
  {
    name: "allow markup in serialized generated error character data",
    file: "src/xml/lib/stanzaError.js",
    before: "CHARACTER_DATA.has(child.local)",
    after: "false",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get checks serialized diagnostic markup$",
  },
  {
    name: "bypass serialized outgoing error content validation",
    file: "src/connection/index.js",
    before: "errorValidator = createStanzaErrorValidator(this.NS);",
    after: "errorValidator = undefined;",
    suite: "conformance/rfc6120-outgoing-errors.test.ts",
    test: "send rejects message error type foo before wire/SM$",
  },
  {
    name: "allow a core error in a non-error message",
    file: "src/connection/index.js",
    before: 'stanzaType !== "error"',
    after: "false",
    suite: "conformance/rfc6120-outgoing-errors.test.ts",
    test: "send rejects message core error with stanza type absent before wire/SM$",
  },
  {
    name: "accept multiple outgoing core errors",
    file: "src/connection/index.js",
    before: "stanzaErrors !== 1",
    after: "stanzaErrors < 1",
    suite: "conformance/rfc6120-outgoing-errors.test.ts",
    test: "sendMany rejects presence two core errors before wire/SM$",
  },
  {
    name: "reject permitted ordinary error condition markup",
    file: "src/xml/lib/stanzaError.js",
    before: "child.uri === NS_STANZA && CHARACTER_DATA.has(child.local)",
    after: "child.uri === NS_STANZA",
    suite: "conformance/rfc6120-outgoing-errors.test.ts",
    test: "send preserves message ordinary registered condition permits opaque attributes and markup$",
  },
  {
    name: "apply core error validation to foreign stanza-named nonzas",
    file: "src/connection/index.js",
    before: 'namespace === this.NS &&\n        (name === "message"',
    after: '(name === "message"',
    suite: "conformance/rfc6120-outgoing-errors.test.ts",
    test: "send preserves foreign stanza-named nonzas$",
  },
  {
    name: "lose inherited namespace bindings while constructing replies",
    file: "src/iq/callee.js",
    before: "Object.assign(element.attrs, namespaces);",
    after: "// Do not materialize inherited namespace bindings.",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get preserves an ordinary result payload's inherited namespace bindings$",
  },
  {
    name: "reject a legal qualified foreign error payload",
    file: "src/iq/callee.js",
    before: "(!reply.getNS() || reply.getNS() === stanza.getNS())",
    after: "true",
    suite: "conformance/rfc6120-generated-errors.test.ts",
    test: "generated get preserves qualified foreign unprefixed error as a result$",
  },
  {
    name: "allow generated standalone declarations",
    file: "src/xml/lib/parseDocument.js",
    before: "standalone !== undefined",
    after: "false",
    suite: "conformance/rfc6120-outgoing-xml.test.ts",
    test: 'send rejects an outgoing standalone="no" declaration$',
  },
  {
    name: "prohibit allowed incoming standalone declarations",
    file: "src/xml/lib/parseDocument.js",
    before: "direction === XML_DIRECTION.OUTPUT &&",
    after: "",
    suite: "src/xml/test/validateDocument.test.js",
    test: "document and incoming XMPP grammar preserve standalone=no$",
  },
  {
    name: "trust a public identity hint for implicit senders",
    file: "src/connection/lib/negotiation.js",
    before: "return connections.get(entity)?.account ?? undefined;",
    after: "return entity.jid?.bare().toString();",
    suite: "conformance/rfc6120-stanza-addressing.test.ts",
    test: "confirmed sender and explicit addresses / sasl / message$",
  },
  {
    name: "retain account authority after socket closure",
    file: "src/connection/index.js",
    before:
      'this._detachParser();\n    resetConnection(this);\n    this._status("disconnect",',
    after: 'this._detachParser();\n    this._status("disconnect",',
    suite: "src/middleware/test/IncomingContext.test.js",
    test: "socket closure invalidates the confirmed sender before disconnect$",
  },
  {
    name: "snapshot a public identity hint for resumption",
    file: "src/stream-management/index.js",
    before: "session = { id, account: getAccount(entity) };",
    after: "session = { id, account: entity.jid?.bare().toString() };",
    suite: "conformance/rfc6120-stanza-addressing.test.ts",
    test: "verified resumption preserves the implicit account / mutated-hints$",
  },
  {
    name: "lose confirmed account on ordinary resumption",
    file: "src/stream-management/index.js",
    before: "confirmIdentity(entity, jid(session.account));",
    after: "// Do not restore the retained account.",
    suite: "conformance/rfc6120-stanza-addressing.test.ts",
    test: "verified resumption preserves the implicit account / ordinary$",
  },
  {
    name: "send serialized frames with a leading non-XML character",
    file: "src/websocket/lib/Socket.js",
    before: "!data.startsWith(XML_START_CHARACTER)",
    after: "false",
    suite: "conformance/rfc7395-outgoing-framing.test.ts",
    test: "send rejects serialized leading",
  },
  {
    name: "allow raw writes to bypass the frame boundary",
    file: "src/websocket/lib/Socket.js",
    before: "!data.startsWith(XML_START_CHARACTER)",
    after: "false",
    suite: "conformance/rfc7395-outgoing-framing.test.ts",
    test: "raw write rejects a frame beginning",
  },
  {
    name: "send the raw domain after preparing routing authority",
    file: "src/connection/lib/negotiation.js",
    before: "return state.server;",
    after: "return domain;",
    suite: "conformance/rfc6120-stream-headers.test.ts",
    test: "header and routing use the same prepared domain / open / A-label$",
  },
  {
    name: "trust a different serialized root namespace",
    file: "src/connection/index.js",
    before: "tag.uri !== namespace ||",
    after: "false ||",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send cannot serialize unsupported server content from a client Element$",
  },
  {
    name: "trust a different serialized root name",
    file: "src/connection/index.js",
    before: "tag.local !== name ||",
    after: "false ||",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send rejects a serializer that changes the stanza root name$",
  },
  {
    name: "ignore serialized stanza addressing",
    file: "src/connection/index.js",
    before: "tag.attributes[attribute]?.value !== expected ||",
    after: "false ||",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send checks the serialized destination during binding / tree to=example.test$",
  },
  {
    name: "ignore post-serializer replay metadata changes",
    file: "src/connection/index.js",
    before: "actual !== expected",
    after: "false",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send rejects serializer side effects / tree ID changes while wire keeps the original stanza ID$",
  },
  {
    name: "hide core stanza classification behind a prefix",
    file: "src/connection/index.js",
    before: "elementName !== name || element.name !== name",
    after: "false",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send rejects serializer side effects / prefixed core tree serializes an unprefixed remote stanza$",
  },
  {
    name: "capture metadata after a caller serializer runs",
    file: "src/connection/index.js",
    before: "const name = element.getName();",
    after: "element.toString();\n    const name = element.getName();",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "send rejects serializer side effects / destination changes to a remote peer in both tree and wire$",
  },
  {
    name: "ignore scalar namespace bindings during preflight",
    file: "src/connection/index.js",
    before: "element.attrs[attribute] = value.toString(10);",
    after: "// Ignore the serialized namespace value.",
    suite: "conformance/rfc6120-serialized-stanzas.test.ts",
    test: "valid serializer and original Element / CJS Element with scalar default namespace false$",
  },
  {
    name: "normalize CJS attribute whitespace into spaces",
    file: "node_modules/ltx/lib/escape.js",
    before: "/[\"&'<>\\t\\n\\r]/g",
    after: "/[\"&'<>]/g",
    suite: "src/xml/test/attribute-values.test.js",
    test: "CJS Element preserves attribute",
  },
  {
    name: "normalize ESM attribute whitespace into spaces",
    file: "node_modules/ltx/src/escape.js",
    before: "/[\"&'<>\\t\\n\\r]/g",
    after: "/[\"&'<>]/g",
    suite: "src/xml/test/attribute-values.test.js",
    test: "ESM Element preserves attribute",
  },
  {
    name: "open without an explicit server target",
    file: "src/connection/lib/negotiation.js",
    before: 'state.server = jid("", domain).domain;',
    after: 'state.server = domain ? jid("", domain).domain : null;',
    suite: "conformance/rfc6120-stream-headers.test.ts",
    test: "invalid opening target rejects before any frame and permits recovery / empty$",
  },
  {
    name: "change stream state before validating the target",
    file: "src/connection/index.js",
    before:
      'const preparedDomain = resetStream(this, domain);\n    this._status("opening");\n    this.#closing = false;',
    after:
      'this._status("opening");\n    this.#closing = false;\n    const preparedDomain = resetStream(this, domain);',
    suite: "conformance/rfc6120-stream-headers.test.ts",
    test: "invalid opening target rejects before any frame and permits recovery / localpart$",
  },
  {
    name: "send malformed configured stream language",
    file: "src/connection/index.js",
    before: 'if (lang != null && lang !== "" && !isLanguageTag(lang)) {',
    after: "if (false) {",
    suite: "conformance/rfc6120-language-tags.test.ts",
    test: "reject malformed configured stream language.*not a tag.*before wire emission$",
  },
  {
    name: "trust tree language instead of serialized output",
    file: "src/connection/index.js",
    before: 'const lang = tag.attributes["xml:lang"]?.value;',
    after: "const lang = undefined;",
    suite: "conformance/rfc6120-language-tags.test.ts",
    test: "send validates actual serialized language / serialized document$",
  },
  {
    name: "allow non-ASCII private-use and extension subtags",
    file: "src/xml/lib/language.js",
    before: " || /[^A-Za-z0-9-]/.test(value)",
    after: "",
    suite: "conformance/rfc6120-language-tags.test.ts",
    test: "reject malformed configured stream language.*en-u-ÄA.*before wire emission$",
  },
  {
    name: "allow repeated language variants",
    file: "src/xml/lib/language.js",
    before: "variants.has(variant)",
    after: "false",
    suite: "src/xml/test/language.test.js",
    test: "reject repeated variant or singleton in sl-rozaj-ROZAJ$",
  },
  {
    name: "allow repeated language extension singletons",
    file: "src/xml/lib/language.js",
    before: "extensions.has(singleton)",
    after: "false",
    suite: "src/xml/test/language.test.js",
    test: "reject repeated variant or singleton in en-u-ca-gregory-U-nu-latn$",
  },
  {
    name: "allow reserved language extlang positions",
    file: "src/xml/lib/language.js",
    before:
      'if (subtags[0].length <= 3 && /^[a-z]{3}$/.test(subtags[index] ?? "")) {',
    after:
      'while (subtags[0].length <= 3 && /^[a-z]{3}$/.test(subtags[index] ?? "")) {',
    suite: "src/xml/test/language.test.js",
    test: "reject permanently reserved extlang positions in zh-cmn-yue$",
  },
  {
    name: "reject grandfathered language alternatives",
    file: "src/xml/lib/language.js",
    before: "GRANDFATHERED.has(tag)",
    after: "false",
    suite: "src/xml/test/language.test.js",
    test: "accept grandfathered i-ami case-insensitively$",
  },
  {
    name: "inherit through a cancelled default namespace",
    file: "node_modules/ltx/lib/Element.js",
    before: 'if (this.attrs.xmlns || this.attrs.xmlns === "") {',
    after: "if (this.attrs.xmlns) {",
    suite: "conformance/rfc6120-namespace-scope.test.ts",
    test: "correlated IQ respects scope / cancelled error$",
  },
  {
    name: "drop namespace cancellation from the ESM constructor",
    file: "node_modules/ltx/src/Element.js",
    before: 'if (this.attrs.xmlns || this.attrs.xmlns === "") {',
    after: "if (this.attrs.xmlns) {",
    suite: "src/xml/test/namespace-scope.test.js",
    test: "ltx ES module exports preserve explicit cancellation$",
  },
  {
    name: "generate prefixes for XMPP content elements",
    file: "src/connection/index.js",
    before: "tag.prefix &&\n            tag.uri === this.NS",
    after: "false",
    suite: "conformance/rfc6120-content-prefixes.test.ts",
    test: "send rejects a prefixed content element.*custom serializer root$",
  },
  {
    name: "dispatch prefixed XMPP content descendants",
    file: "src/connection/index.js",
    before: "hasContentPrefix(element, this.NS)) {\n      return;",
    after: "false) {\n      return;",
    suite: "conformance/rfc6120-content-prefixes.test.ts",
    test: "receiver ignores or closes.*prefixed error child$",
  },
  {
    name: "ignore nested XMPP content prefixes",
    file: "src/connection/lib/hasContentPrefix.js",
    before: "  for (const child of element.children) {",
    after: "  return false;\n  for (const child of element.children) {",
    suite: "conformance/rfc6120-content-prefixes.test.ts",
    test: "receiver ignores or closes.*prefixed content inside foreign payload$",
  },
  {
    name: "reject foreign prefixes by spelling instead of namespace",
    file: "src/connection/index.js",
    before: "tag.prefix &&\n            tag.uri === this.NS",
    after: "tag.prefix",
    suite: "conformance/rfc6120-content-prefixes.test.ts",
    test: "send preserves permitted prefixes.*a foreign prefixed root$",
  },
  {
    name: "serialize a different document after XML validation",
    file: "src/connection/index.js",
    before: "    await this.write(source);",
    after: "    await this.write(element.toString());",
    suite: "conformance/rfc6120-outgoing-xml.test.ts",
    test: "send writes the exact document validated once$",
  },
  {
    name: "write malformed outgoing XML without validation",
    file: "src/xml/lib/parseDocument.js",
    before: "  parser.write(source).close();\n}\n\n/** Validate",
    after: "  /* XML validation bypassed. */\n}\n\n/** Validate",
    suite: "conformance/rfc6120-outgoing-xml.test.ts",
    test: "send rejects malformed XML.*root prefix is unbound$",
  },
  {
    name: "accept unpaired UTF-16 before a forbidden XML character",
    file: "src/xml/lib/parseDocument.js",
    before: "UNPAIRED_SURROGATE.test(source)",
    after: "false",
    suite: "conformance/rfc6120-outgoing-xml.test.ts",
    test: "send rejects malformed XML.*high surrogate before NUL in descendant text$",
  },
  {
    name: "restrict valid outgoing XML to the receive byte limit",
    file: "src/connection/index.js",
    before: "      validateDocument(",
    after:
      "      if (source.length > 1024 * 1024) throw new Error('size limit');\n      validateDocument(",
    suite: "conformance/rfc6120-outgoing-xml.test.ts",
    test: "send preserves well-formed XML.*receive-side byte limit$",
  },
  {
    name: "send remote stanzas before negotiation completes",
    file: "src/connection/index.js",
    before: "!canSendStanza(this, destination)",
    after: "false",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "reject remote stanzas.*start / sasl / authentication",
  },
  {
    name: "restore stale routing authority before stream opening",
    file: "src/connection/index.js",
    before: "async connect(service) {\n    resetConnection(this);",
    after:
      "async connect(service) {\n    resetConnection(this);\n    if (this.jid) { confirmIdentity(this, this.jid); completeNegotiation(this); }",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "ordinary remote replay.* / valid$",
  },
  {
    name: "retain a former authenticated account on reconnect",
    file: "src/connection/lib/negotiation.js",
    before: "account: null, server: null, complete: false",
    after:
      "account: connections.get(entity)?.account ?? null, server: null, complete: false",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "reject remote stanzas.*reconnect / sasl / authentication",
  },
  {
    name: "retain remote routing authority across stream restart",
    file: "src/connection/lib/negotiation.js",
    before: "state.complete = false;",
    after: "",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "reopening retains only authenticated self authority / sasl$",
  },
  {
    name: "derive connected server authority from mutable options",
    file: "src/connection/lib/negotiation.js",
    before: "destination.domain === server",
    after: 'destination.domain === jid("", entity.options.domain).domain',
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "server authority follows the opened target.*changed options",
  },
  {
    name: "drop validated remote resumption authority",
    file: "src/stream-management/index.js",
    before: "    completeNegotiation(entity);",
    after: "",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "ordinary remote replay.* / valid$",
  },
  {
    name: "use mutable configured names as authenticated identities",
    file: "src/connection/lib/negotiation.js",
    before:
      "return account !== null && destination.bare().toString() === account;",
    after:
      "return destination.bare().toString() === `${entity.options.username}@${entity.options.domain}`;",
    suite: "conformance/rfc6120-stanza-routing.test.ts",
    test: "server, confirmed self and extension boundaries.*sasl2",
  },
  {
    name: "classify foreign roots as core stanzas",
    file: "src/connection/index.js",
    before: "element.getNS() === this.NS &&",
    after: "",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "cannot complete an IQ result",
  },
  {
    name: "route foreign IQ replies",
    file: "src/iq/caller.js",
    before: " || !this.entity.isStanza(stanza)",
    after: "",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "cannot complete an IQ error",
  },
  {
    name: "dispatch foreign IQ requests",
    file: "src/iq/callee.js",
    before: " || !entity.isStanza(ctx.stanza)",
    after: "",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "cannot invoke IQ handlers",
  },
  {
    name: "count incoming foreign nonzas as handled stanzas",
    file: "src/stream-management/index.js",
    before: "if (entity.isStanza(stanza)) {",
    after: 'if (["message", "presence", "iq"].includes(stanza.name)) {',
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "stays outside stanza delivery and counting",
  },
  {
    name: "queue outgoing foreign nonzas for acknowledgement",
    file: "src/stream-management/index.js",
    before: "if (!entity.isStanza(stanza)) {",
    after: 'if (!["message", "presence", "iq"].includes(stanza.name)) {',
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "stays outside stanza validation and acknowledgements",
  },
  {
    name: "interpret extension addresses as XMPP identities",
    file: "src/middleware/index.js",
    before: "ctx = entity.isStanza(stanza)",
    after: "ctx = true",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "stays outside stanza delivery and counting",
  },
  {
    name: "accept server content on a client stream",
    file: "src/connection/index.js",
    before: "element.getNS() === NS_JABBER_SERVER) {\n      const error",
    after: "false) {\n      const error",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "unsupported server content namespace closes atomically / iq result",
  },
  {
    name: "generate server content on a client stream",
    file: "src/connection/index.js",
    before: "element.getNS() === NS_JABBER_SERVER) {\n      throw",
    after: "false) {\n      throw",
    suite: "conformance/rfc6120-namespaces.test.ts",
    test: "outgoing server content namespace rejects before writing",
  },
  {
    name: "accept a different ordinary SM resumption ID",
    file: "src/stream-management/index.js",
    before: "if (!sm.id || resumed.attrs.previd !== sm.id) {",
    after: "if (false) {",
    suite: "conformance/xep0198-resumption.test.ts",
    test: "ordinary resumption.*mismatched",
  },
  {
    name: "accept a different inline SM resumption ID",
    file: "src/stream-management/index.js",
    before: "if (!sm.id || resumed.attrs.previd !== sm.id) {",
    after: "if (false) {",
    suite: "conformance/xep0198-resumption.test.ts",
    test: "inline resumption.*mismatched",
  },
  {
    name: "trim opaque SM resumption IDs",
    file: "src/stream-management/index.js",
    before: "resumed.attrs.previd !== sm.id",
    after: "resumed.attrs.previd?.trim() !== sm.id.trim()",
    suite: "conformance/xep0198-resumption.test.ts",
    test: "ordinary resumption.*trimmed",
  },
  {
    name: "case-fold opaque SM resumption IDs",
    file: "src/stream-management/index.js",
    before: "resumed.attrs.previd !== sm.id",
    after: "resumed.attrs.previd?.toLowerCase() !== sm.id.toLowerCase()",
    suite: "conformance/xep0198-resumption.test.ts",
    test: "inline resumption.*case-changed",
  },
  {
    name: "leave SASL2 post-success features unbounded",
    file: "src/sasl2/index.js",
    before: "expectFeatures();",
    after: "",
    suite: "conformance/xep0388-features.test.ts",
    test: "local deadline / start / classic",
  },
  {
    name: "require features after successful inline resumption",
    file: "src/sasl2/index.js",
    before: "if (!resumed) {",
    after: "if (true) {",
    suite: "conformance/xep0388-features.test.ts",
    test: "omits features / resume / missing",
  },
  {
    name: "arm the SASL2 features deadline after proof verification",
    file: "src/sasl2/index.js",
    before: "expectFeatures();",
    after: "streamFeatures.authentication.then(() => expectFeatures());",
    suite: "conformance/xep0388-features.test.ts",
    test: "cancel the deadline / classic / immediate",
  },
  {
    name: "exempt failed inline resumption from the deadline",
    file: "src/sasl2/index.js",
    before: 'element.getChild("resumed", NS_SM);',
    after:
      '(element.getChild("resumed", NS_SM) || element.getChild("failed", NS_SM));',
    suite: "conformance/xep0388-features.test.ts",
    test: "omits features / failed-resume / missing",
  },
  {
    name: "leak the SASL2 success observer",
    file: "src/sasl2/index.js",
    before: '() => entity.removeListener("nonza", onSuccess),',
    after: "() => {},",
    suite: "conformance/xep0388-features.test.ts",
    test: "isolates a replacement / stop",
  },
  {
    name: "reuse the former resource after stream conflict",
    file: "src/resource-binding/index.js",
    before: 'error instanceof StreamError && error.condition === "conflict"',
    after: "false",
    suite: "conformance/rfc6120-binding.test.ts",
    test: "resource selection on reconnect / fixed",
  },
  {
    name: "compare conflicted resources before Unicode preparation",
    file: "src/resource-binding/index.js",
    before: "(!selected || selected === conflictedResource)",
    after: "(!selected || requested === conflictedResource)",
    suite: "conformance/rfc6120-binding.test.ts",
    test: "resource selection on reconnect / normalized",
  },
  {
    name: "retain feature deadline during local close",
    file: "src/stream-features/index.js",
    before: 'entity.on("closing", clearFeatureTimer);',
    after: "",
    suite: "conformance/rfc6120-streams.test.ts",
    test: "clear features deadline / silent stop",
  },
  {
    name: "enable SM before SASL2 inline binding finishes",
    file: "src/stream-management/stream-feature.js",
    before: "await streamFeatures.authentication;",
    after: "",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "permits inline binding only after verification / TEST-NEGOTIATION",
  },
  {
    name: "leave stream features unbounded",
    file: "src/stream-features/index.js",
    before: 'entity.on("open", expectFeatures);',
    after: 'entity.on("unused-open", expectFeatures);',
    suite: "conformance/rfc6120-streams.test.ts",
    test: "local features deadline / start / initial",
  },
  {
    name: "retain feature deadline after negotiation",
    file: "src/stream-features/index.js",
    before: "    clearFeatureTimer();\n    if (\n      stanza",
    after: "    if (\n      stanza",
    suite: "conformance/rfc6120-streams.test.ts",
    test: "clear features deadline / online",
  },
  {
    name: "enable Stream Management before binding",
    file: "src/stream-management/stream-feature.js",
    before: 'if (entity.status !== "online")',
    after: "if (false)",
    suite: "conformance/rfc6120-streams.test.ts",
    test: "SM without binding",
  },
  {
    name: "accept multi-payload IQ results",
    file: "src/iq/caller.js",
    before: "children.length > 1 || errors.length !== 0",
    after: "errors.length !== 0",
    suite: "conformance/rfc6120-iq.test.ts",
    test: "two result payloads",
  },
  {
    name: "omit required IQ response ID",
    file: "src/iq/callee.js",
    before: 'id: stanza.attrs.id ?? "",',
    after: "id: stanza.attrs.id,",
    suite: "conformance/rfc6120-iq.test.ts",
    test: "request get $",
  },
  {
    name: "accept unknown stanza error conditions as understood",
    file: "src/error/index.js",
    before: "(!known || known.has(condition))",
    after: "true",
    suite: "conformance/rfc6120-iq.test.ts",
    test: "namespaced stanza error / future-condition",
  },
  {
    name: "leave unsupported features pending",
    file: "src/stream-features/index.js",
    before: 'entity.status === "open"',
    after: "false",
    suite: "conformance/rfc6120-streams.test.ts",
    test: "empty before authentication",
  },
  {
    name: "remove reconnect jitter",
    file: "src/reconnect/index.js",
    before: "0.5 + Math.random() / 2",
    after: "1",
    suite: "./src/reconnect/test.js",
    test: "randomizes the initial delay",
  },
  {
    name: "remove reconnect backoff",
    file: "src/reconnect/index.js",
    before: "this.#attempt++;",
    after: "",
    suite: "./src/reconnect/test.js",
    test: "grows to a cap",
  },
  {
    name: "bind before asynchronous SASL2 proof verification completes",
    file: "src/resource-binding/index.js",
    before: "await streamFeatures.authentication;",
    after: "",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "SASL2 success permits classic binding",
  },
  {
    name: "accept overlapping SASL messages",
    file: "src/sasl/exchange.js",
    before: "responding ||",
    after: "false ||",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "overlapping success",
  },
  {
    name: "respond after protocol abort",
    file: "src/sasl/exchange.js",
    before: "aborted = true;",
    after: "aborted = false;",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "abort permits",
  },
  {
    name: "accept non-bare authorization identities",
    file: "src/sasl/credentials.js",
    before: "if (!identity.local || identity.resource)",
    after: "if (false)",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "authorization identity",
  },
  {
    name: "invent an authentication realm from the domain",
    file: "src/sasl/credentials.js",
    before: "serviceName: domain,",
    after: "serviceName: domain, realm: domain,",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "no implicit authentication realm",
  },
  {
    name: "reenter SASL from duplicate features",
    file: "src/sasl/index.js",
    before: "streamFeatures.authenticating || streamFeatures.authenticated",
    after: "false",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "duplicate features",
  },
  {
    name: "omit generic fallback for unknown SASL conditions",
    file: "src/sasl/lib/SASLError.js",
    before: "CONDITIONS.has(condition?.name)",
    after: "!!condition",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "unknown/malformed failure",
  },
  {
    name: "allow callback downgrade to PLAIN",
    file: "src/client/lib/createOnAuthenticate.js",
    before: "mechanism === PLAIN && mechanisms.indexOf(PLAIN) > 0",
    after: "false",
    suite: "src/client/test/authentication-policy.test.js",
    test: "policy / downgrade",
  },
  {
    name: "retain connection after exhausted authentication",
    file: "src/client/lib/createOnAuthenticate.js",
    before: "if (socket && entity.socket === socket)",
    after: "if (false)",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "exhausted authentication",
  },
  {
    name: "omit authenticated state after SASL2",
    file: "src/sasl2/index.js",
    before: "streamFeatures.authenticated = true;",
    after: "streamFeatures.authenticated = false;",
    suite: "conformance/rfc6120-sasl-negotiation.test.ts",
    test: "SASL2 success permits classic binding",
  },
  {
    name: "accept a bare binding identity",
    file: "src/resource-binding/index.js",
    before: "if (!jid.local || !jid.resource)",
    after: "if (false)",
    suite: "conformance/rfc6120-binding.test.ts",
    test: "invalid binding result",
  },
  {
    name: "bind before authentication",
    file: "src/resource-binding/index.js",
    before: "if (!streamFeatures.authenticated)",
    after: "if (false)",
    suite: "conformance/rfc6120-binding.test.ts",
    test: "premature binding",
  },
  {
    name: "skip SASL success encoding validation without final hook",
    file: "src/sasl/exchange.js",
    before: "const final = mech.binary ? decodeBytes(data) : decode(data);",
    after:
      "const final = namespace === SASL && !mech.final ? null : mech.binary ? decodeBytes(data) : decode(data);",
    suite: "conformance/rfc6120-sasl-base64.test.ts",
    test: "success-without-hook",
  },
  {
    name: "skip SASL2 success encoding validation without final hook",
    file: "src/sasl/exchange.js",
    before: "const final = mech.binary ? decodeBytes(data) : decode(data);",
    after:
      "const final = namespace !== SASL && !mech.final ? null : mech.binary ? decodeBytes(data) : decode(data);",
    suite: "conformance/rfc6120-sasl-base64.test.ts",
    test: "success-without-hook",
  },
  {
    name: "accept noncanonical SASL Base64",
    file: "src/util/base64.js",
    before: "if (encode(bytes) !== data)",
    after: "if (false)",
    suite: "conformance/rfc6120-sasl-base64.test.ts",
    test: "rejects invalid Base64",
  },
  {
    name: "allow callback to bypass PLAIN transport policy",
    file: "src/client/lib/createOnAuthenticate.js",
    before: "mechanism === PLAIN && !entity.isSecure()",
    after: "false",
    suite: "src/client/test/authentication-policy.test.js",
    test: "policy / insecure",
  },
  {
    name: "allow callback to select unoffered mechanisms",
    file: "src/client/lib/createOnAuthenticate.js",
    before: "!mechanisms.includes(mechanism)",
    after: "false",
    suite: "src/client/test/authentication-policy.test.js",
    test: "policy / unoffered",
  },
  {
    name: "restart without successful SASL authentication",
    file: "src/client/lib/createOnAuthenticate.js",
    before: "if (!authenticated)",
    after: "if (false)",
    suite: "conformance/rfc6120-sasl.test.ts",
    test: "callback cannot authorize restart",
  },
  {
    name: "omit server-first SASL initiation",
    file: "src/sasl/index.js",
    before: 'xml("auth", { xmlns: NS, mechanism: mech.name }, response)',
    after:
      'mech.clientFirst && xml("auth", { xmlns: NS, mechanism: mech.name }, response)',
    suite: "conformance/rfc6120-sasl.test.ts",
    test: "server-first exchange",
  },
  {
    name: "omit explicit empty SASL initial response",
    file: "src/sasl/index.js",
    before: 'encode(await mech.response(creds)) || "="',
    after: "encode(await mech.response(creds))",
    suite: "conformance/rfc6120-sasl.test.ts",
    test: "empty-initial exchange",
  },
  {
    name: "discard binary SASL responses",
    file: "src/sasl/exchange.js",
    before: 'response == null ? "" : encode(response)',
    after: 'typeof response === "string" ? encode(response) : ""',
    suite: "conformance/rfc6120-sasl.test.ts",
    test: "binary exchange",
  },
  {
    name: "reject explicit empty SASL success data",
    file: "src/sasl/exchange.js",
    before: 'element.text() === "="',
    after: "false",
    suite: "conformance/rfc6120-sasl.test.ts",
    test: "empty-final exchange",
  },
  {
    name: "omit SASLprep password normalization",
    file: "src/sasl-scram/index.js",
    before: 'password = saslprep(password, "stored");',
    after: "",
    suite: "conformance/rfc5802.test.js",
    test: "prepares credentials before hashing",
  },
  {
    name: "allow unassigned stored SCRAM passwords",
    file: "src/sasl-scram/saslprep.js",
    before: 'if (profile === "stored") {',
    after: "if (false) {",
    suite: "conformance/rfc4013.test.js",
    test: "stored password rejects",
  },
  {
    name: "omit SASLprep bidi enforcement",
    file: "src/sasl-scram/saslprep.js",
    before: "if (RANDAL.test(normalized)) {",
    after: "if (false) {",
    suite: "conformance/rfc4013.test.js",
    test: "prohibited output / bidi",
  },
  {
    name: "ignore SCRAM server signature",
    file: "src/sasl-scram/index.js",
    before: "if (!valid) {",
    after: "if (false) {",
    suite: "conformance/rfc5802.test.js",
    test: "reject missing, forged or ambiguous",
  },
  {
    name: "skip SASL final verification",
    file: "src/sasl/exchange.js",
    before: "if (mech.final) {",
    after: "if (mech.final && namespace !== SASL) {",
    suite: "conformance/rfc5802-wire.test.ts",
    test: "missing server proof",
  },
  {
    name: "skip SASL2 verification when proof is absent",
    file: "src/sasl/exchange.js",
    before: "if (mech.final) {",
    after: "if (mech.final && (namespace === SASL || data)) {",
    suite: "conformance/rfc5802-wire.test.ts",
    test: "missing server proof",
  },
  {
    name: "accept expired XRD metadata",
    file: "src/resolve/lib/http.js",
    before: "!isUnexpired(expires[0])",
    after: "false",
    suite: "conformance/xep0156.test.js",
    test: "XRD expiry:",
  },
  {
    name: "compare XRD relation types case-sensitively",
    file: "src/resolve/lib/http.js",
    before: "METHODS.get(attrs.rel?.toLowerCase())",
    after: "METHODS.get(attrs.rel)",
    suite: "conformance/xep0156.test.js",
    test: "relation and URI scheme comparisons",
  },
  {
    name: "remove the HTTPS discovery deadline",
    file: "src/resolve/lib/http.js",
    before: "signal: AbortSignal.timeout(DISCOVERY_TIMEOUT_MS),",
    after: "",
    suite: "conformance/xep0156-https.test.ts",
    test: "local deadline bounds HTTPS discovery: body",
  },
  {
    name: "follow discovery redirects including plaintext targets",
    file: "src/resolve/lib/http.js",
    before: 'redirect: "error",',
    after: 'redirect: "follow",',
    suite: "conformance/xep0156-https.test.ts",
    test: "redirect policy never contacts",
  },
  {
    name: "treat discovery document order as priority",
    file: "src/resolve/lib/alt-connections.js",
    before: "return a.uri < b.uri ? -1 : a.uri > b.uri ? 1 : 0;",
    after: "return 0;",
    suite: "conformance/xep0156.test.js",
    test: "endpoint preference ignores document order",
  },
  {
    name: "accept resource templates as host-wide endpoints",
    file: "src/resolve/lib/http.js",
    before: "if (attrs.template !== undefined) {",
    after: "if (false) {",
    suite: "conformance/xep0156.test.js",
    test: "excludes resource templates",
  },
  {
    name: "drop decoded Unicode ranges",
    file: "src/util/unicode-ranges.js",
    before: 'return new RegExp(`[${parts.join("")}]`, "u");',
    after: 'return new RegExp("[]", "u");',
    suite: "src/jid/test/unicode.test.js",
    test: "all Unicode 16 property tables preserve",
  },
  {
    name: "omit JID NFC normalization",
    file: "src/jid/lib/precis.js",
    before: 'value = value.toLowerCase().normalize("NFC");',
    after: "value = value.toLowerCase();",
    suite: "conformance/rfc7622.test.js",
    test: "normalizes equivalent identities",
  },
  {
    name: "omit JID byte limits",
    file: "src/jid/lib/precis.js",
    before: "export function checkLength(value) {",
    after: "export function checkLength(value) { return value;",
    suite: "conformance/rfc7622.test.js",
    test: "post-preparation UTF-8 limits",
  },
  {
    name: "omit JID contextual rules",
    file: "src/jid/lib/precis.js",
    before: "if (!valid) {",
    after: "if (false) {",
    suite: "conformance/rfc7622.test.js",
    test: "rejects localpart",
  },
  {
    name: "omit JID bidi checks",
    file: "src/jid/lib/precis.js",
    before: "export function validateBidi(value) {",
    after: "export function validateBidi(value) { return;",
    suite: "conformance/rfc7622.test.js",
    test: "rejects localpart",
  },
  {
    name: "accept IDNA-disallowed identifier characters",
    file: "src/jid/lib/domain.js",
    before: "if (unicode.idnaDisallowed.test(label)) {",
    after: "if (false) {",
    suite: "conformance/rfc7622.test.js",
    test: "rejects domain",
  },
  {
    name: "silently ignore invalid SM counters",
    file: "src/stream-management/index.js",
    before: "if (!valid || distance > sm.outbound_q.length) {",
    after: "if (!valid || distance > sm.outbound_q.length) { return;",
    suite: "conformance/xep0198.test.ts",
    test: "invalid SM acknowledgement",
  },
  {
    name: "omit SM inbound counter rollover",
    file: "src/stream-management/index.js",
    before: "sm.inbound = (sm.inbound + 1) % COUNTER_MODULUS;",
    after: "sm.inbound += 1;",
    suite: "src/stream-management/counters.test.js",
    test: "received stanza counter wraps",
  },
  {
    name: "accept an IQ reply from an unrelated sender",
    file: "src/iq/caller.js",
    before: "!deferred || !replyMatches(stanza.attrs.from, deferred)",
    after: "!deferred",
    suite: "conformance/rfc6120.test.ts",
    test: "IQ ignores a forged",
  },
  {
    name: "accept an unsupported stream version",
    file: "src/websocket/lib/FramedParser.js",
    before: "if (!version || Number(version[1]) !== 1)",
    after: "if (false)",
    suite: "src/websocket/test/frames.test.js",
    test: "rejects unsupported peer version",
  },
  {
    name: "omit the outgoing language context",
    file: "src/websocket/lib/Connection.js",
    before:
      'element.attrs["xml:lang"] ??= this.root?.attrs["xml:lang"];\n    return super.send',
    after: "return super.send",
    suite: "conformance/rfc7395.test.ts",
    test: "every outgoing stanza carries its language",
  },
  {
    name: "remove the document byte limit",
    file: "src/xml/lib/parseDocument.js",
    before: "export const MAX_XML_BYTES = 1024 * 1024;",
    after: "export const MAX_XML_BYTES = Infinity;",
    suite: "src/xml/test/limits.test.js",
    test: "document byte limit",
  },
  {
    name: "remove the document depth limit",
    file: "src/xml/lib/parseDocument.js",
    before: "const MAX_XML_DEPTH = 64;",
    after: "const MAX_XML_DEPTH = Infinity;",
    suite: "src/xml/test/limits.test.js",
    test: "document depth limit",
  },
  {
    name: "accept an unfinished XML document",
    file: "src/xml/lib/parseDocument.js",
    before: "parser.write(source).close();\n  return root;",
    after: "parser.write(source);\n  return root;",
    suite: "src/websocket/test/frames.test.js",
    test: "rejects a whole malformed frame",
  },
  {
    name: "report the wrong framing namespace condition",
    file: "src/websocket/lib/FramedParser.js",
    before: 'error.condition = "invalid-namespace";',
    after: 'error.condition = "bad-format";',
    suite: "src/websocket/test/frames.test.js",
    test: "reports invalid-namespace",
  },
  {
    name: "accept an unnegotiated subprotocol",
    file: "src/websocket/lib/Socket.js",
    before: "this.socket.protocol !== SUBPROTOCOL",
    after: "false",
    suite: "src/websocket/test/subprotocol.test.js",
    test: "rejects negotiated subprotocol",
  },
  {
    name: "omit the outgoing stanza namespace",
    file: "src/websocket/lib/Connection.js",
    before: "send(element, ...args) {\n    element.attrs.xmlns ??= this.NS;",
    after: "send(element, ...args) {\n    /* namespace omitted */",
    suite: "conformance/rfc7395.test.ts",
    test: "sends UTF-8 text",
  },
  {
    name: "open a stream to the wrong domain",
    file: "src/connection/index.js",
    before: "headerElement.attrs.to = preparedDomain;",
    after: 'headerElement.attrs.to = "wrong.test";',
    suite: "conformance/rfc7395.test.ts",
    test: "first message is a standalone",
  },
];

// Mutate disposable copies; never alter the worktree or shared dependencies.
for (const mutation of mutations) {
  const directory = mkdtempSync(join(tmpdir(), "xmpp-mutation-"));
  try {
    cpSync("src", join(directory, "src"), { recursive: true });
    cpSync("test/support", join(directory, "test/support"), {
      recursive: true,
    });
    for (const file of [
      "package.json",
      "tsconfig.json",
      "bunfig.toml",
      "conformance/rfc7395.test.ts",
      "conformance/rfc7395-outgoing-framing.test.ts",
      "conformance/rfc6120.test.ts",
      "conformance/rfc6120-stanza-routing.test.ts",
      "conformance/rfc6120-stanza-addressing.test.ts",
      "conformance/rfc6120-outgoing-xml.test.ts",
      "conformance/rfc6120-content-prefixes.test.ts",
      "conformance/rfc6120-namespace-scope.test.ts",
      "conformance/rfc6120-language-tags.test.ts",
      "conformance/rfc6120-stream-headers.test.ts",
      "conformance/rfc6120-serialized-stanzas.test.ts",
      "conformance/rfc6120-iq.test.ts",
      "conformance/rfc6120-generated-errors.test.ts",
      "conformance/rfc6120-outgoing-iq.test.ts",
      "conformance/rfc6120-outgoing-errors.test.ts",
      "conformance/rfc6120-namespaces.test.ts",
      "conformance/rfc6120-streams.test.ts",
      "conformance/rfc6120-binding.test.ts",
      "conformance/rfc6120-sasl.test.ts",
      "conformance/rfc6120-sasl-negotiation.test.ts",
      "conformance/rfc6120-sasl-base64.test.ts",
      "conformance/rfc5802.test.js",
      "conformance/rfc4013.test.js",
      "conformance/rfc5802-wire.test.ts",
      "conformance/xep0198.test.ts",
      "conformance/xep0198-resumption.test.ts",
      "conformance/xep0388-features.test.ts",
      "conformance/xep0156.test.js",
      "conformance/xep0156-https.test.ts",
      "conformance/rfc7622.test.js",
      "conformance/peer.ts",
      "conformance/xml.ts",
    ]) {
      cpSync(file, join(directory, file));
    }
    if (mutation.file.startsWith("node_modules/ltx/")) {
      // Dependency mutations must never follow the shared node_modules symlink.
      mkdirSync(join(directory, "node_modules"));
      for (const dependency of readdirSync("node_modules")) {
        const source = resolve("node_modules", dependency);
        const target = join(directory, "node_modules", dependency);
        if (dependency === "ltx") {
          cpSync(source, target, { recursive: true, dereference: true });
        } else {
          symlinkSync(source, target, "dir");
        }
      }
    } else {
      symlinkSync(
        resolve("node_modules"),
        join(directory, "node_modules"),
        "dir",
      );
    }
    const args = ["test", mutation.suite, "--test-name-pattern", mutation.test];
    const options = {
      cwd: directory,
      encoding: "utf8" as const,
      timeout: MUTATION_TIMEOUT_MS,
    };
    const baseline = spawnSync(process.execPath, args, options);
    if (baseline.status !== 0 || !baseline.stderr.includes("(pass)")) {
      throw new Error(
        `Mutation baseline failed: ${mutation.name}\n${baseline.stderr}`,
      );
    }

    const path = join(directory, mutation.file);
    const source = readFileSync(path, "utf8");
    if (source.split(mutation.before).length !== 2) {
      throw new Error(
        `Mutation target must occur exactly once: ${mutation.name}`,
      );
    }
    writeFileSync(path, source.replace(mutation.before, mutation.after));
    const result = spawnSync(process.execPath, args, options);
    // Crashes and timeouts do not prove that an assertion caught the defect.
    if (
      result.status !== 1 ||
      !result.stderr.includes("error: expect(received)")
    ) {
      throw new Error(
        `Mutation survived or failed outside an assertion: ${mutation.name}\n${result.stderr}`,
      );
    }
    console.log(`Caught mutation: ${mutation.name}`);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}
