"""Emit Unicode 3.2 SASLprep tables; Python's stringprep implements RFC 3454.

Run python3 tools/saslprep-data.py and save stdout as src/sasl-scram/unicode.js.
No network or current-runtime Unicode properties enter the generated data.
"""
import json
import hashlib
import stringprep as tables
import sys
from unicodedata import ucd_3_2_0

assert ucd_3_2_0.unidata_version == "3.2.0"
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


def encode(number):
    result = ""
    while number >= 32:
        result += ALPHABET[(number & 31) | 32]
        number >>= 5
    return result + ALPHABET[number]


def ranges(predicate):
    result = ""
    previous = 0
    start = None
    for point in range(0x110001):
        matches = point < 0x110000 and predicate(chr(point))
        if matches and start is None:
            start = point
        if not matches and start is not None:
            result += encode(start - previous) + encode(point - start)
            previous = point
            start = None
    return result


prohibited = [getattr(tables, "in_table_" + name) for name in
              ["c12", "c21", "c22", "c3", "c4", "c5", "c6", "c7", "c8", "c9"]]
properties = {
    "UNASSIGNED": tables.in_table_a1,
    "NOTHING": tables.in_table_b1,
    "SPACE": tables.in_table_c12,
    "PROHIBITED": lambda char: any(test(char) for test in prohibited),
    "RANDAL": tables.in_table_d1,
    "LCAT": tables.in_table_d2,
}


def prepare(value, profile):
    value = "".join(" " if tables.in_table_c12(c) else c
                    for c in value if not tables.in_table_b1(c))
    # CPython's 3.2 normalizer leaks modern combining classes for unassigned
    # characters: NFKC("a\u0353\u0301") wrongly produces "\u00e1\u0353".
    # UAX #15 versioning requires ccc=0. Protect these with NUL barriers during
    # normalization and restore afterwards. An actual NUL is prohibited.
    if "\0" in value:
        raise ValueError()
    unassigned = iter(c for c in value if tables.in_table_a1(c))
    protected = "".join("\0" if tables.in_table_a1(c) else c for c in value)
    value = "".join(next(unassigned) if c == "\0" else c
                    for c in ucd_3_2_0.normalize("NFKC", protected))
    if any(test(c) for c in value for test in prohibited):
        raise ValueError()
    if profile == "stored" and any(tables.in_table_a1(c) for c in value):
        raise ValueError()
    if any(tables.in_table_d1(c) for c in value):
        if (any(tables.in_table_d2(c) for c in value)
                or not tables.in_table_d1(value[0]) or not tables.in_table_d1(value[-1])):
            raise ValueError()
    return value


if "--oracle" in sys.argv:
    # Independent normalization oracle, including every code point in context.
    for profile in ["query", "stored"]:
        for context in [False, True]:
            digest = hashlib.sha256()
            for point in range(0x110000):
                value = chr(point)
                if context:
                    value = "a" + value + "\u0301"
                try:
                    result = prepare(value, profile)
                except ValueError:
                    result = "!"
                digest.update((str(point) + ":" + result + "\n").encode("utf-8"))
            print(profile, context, digest.hexdigest())
    sys.exit()

print('// Generated by tools/saslprep-data.py; RFC 3454 / Unicode 3.2.0.')
print('import { decodeRanges } from "../util/unicode-ranges.js";')
for name, predicate in properties.items():
    print(f'export const {name} = decodeRanges({json.dumps(ranges(predicate))});')
